
package paquete.servicio.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectJPAEJBSOAP", targetNamespace = "http://soap.servicio.paquete/", wsdlLocation = "http://tgr3591:7001/ServicioSOAPImpl/ProjectJPAEJBSOAP?WSDL")
public class ProjectJPAEJBSOAP
    extends Service
{

    private final static URL PROJECTJPAEJBSOAP_WSDL_LOCATION;
    private final static WebServiceException PROJECTJPAEJBSOAP_EXCEPTION;
    private final static QName PROJECTJPAEJBSOAP_QNAME = new QName("http://soap.servicio.paquete/", "ProjectJPAEJBSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tgr3591:7001/ServicioSOAPImpl/ProjectJPAEJBSOAP?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTJPAEJBSOAP_WSDL_LOCATION = url;
        PROJECTJPAEJBSOAP_EXCEPTION = e;
    }

    public ProjectJPAEJBSOAP() {
        super(__getWsdlLocation(), PROJECTJPAEJBSOAP_QNAME);
    }

    public ProjectJPAEJBSOAP(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTJPAEJBSOAP_QNAME, features);
    }

    public ProjectJPAEJBSOAP(URL wsdlLocation) {
        super(wsdlLocation, PROJECTJPAEJBSOAP_QNAME);
    }

    public ProjectJPAEJBSOAP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTJPAEJBSOAP_QNAME, features);
    }

    public ProjectJPAEJBSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectJPAEJBSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSOAP
     */
    @WebEndpoint(name = "NombreServidorSOAPPort")
    public ServicioSOAP getNombreServidorSOAPPort() {
        return super.getPort(new QName("http://soap.servicio.paquete/", "NombreServidorSOAPPort"), ServicioSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSOAP
     */
    @WebEndpoint(name = "NombreServidorSOAPPort")
    public ServicioSOAP getNombreServidorSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.servicio.paquete/", "NombreServidorSOAPPort"), ServicioSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTJPAEJBSOAP_EXCEPTION!= null) {
            throw PROJECTJPAEJBSOAP_EXCEPTION;
        }
        return PROJECTJPAEJBSOAP_WSDL_LOCATION;
    }

}
